config/routes.rb
Rails.application.routes.draw do
	root to: redirect("#{I18n.default_locale}", status: 302), as: :redirected_root 
	#resources :session, only: [:create, :destroy]
	#get '/session/new', to: redirect('/id/login')
	scope '(:locale)' , :locale => /en|id/ do
	  	root 'home#index'
	  	
	  	get 'course', to: ("course#index")
	  	get 'blog', to: ("blog#index")
	  	#get '/sessions/new', to: redirect('/%{locale}/login')

	  	#get '/login', to: 'sessions#new', as: 'login'
	    #get '/logout', to: 'sessions#destroy', as: 'logout'

	    # resources :sessions, only: [:create] do
	    #     collection do
	    #       get :oauth
	    #     end
	    # end
  	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
	UTM = %w(utm_source utm_medium utm_campaign utm_term)
	AVAILABLE_COUNTRY = ['en', 'id']

	before_action :set_locale
	 
	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	end
	def default_url_options
	  { locale: I18n.locale }
	end
	protected

	# Derive the model name from the controller. egs UsersController will return User
	def self.permission
		return name = controller_name.classify.constantize
	end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_title(title = nil)
	    if title
	      	# flush true means clear the content_for page_title first.
	      	content_for(:page_title, flush: true) { title[0...60] }
	    else
	      	content_for?(:page_title) ? content_for(:page_title) : t('meta.default.title') # or default page title
	    end
	end

	def meta_description(description = nil)
	    # Better to have empty description rather than duplicate
	    description = description[0..290] if description.present?
	    content_for(:meta_description, flush: true) { h description }
	end

	# used to render meta keywords
	def meta_keywords(keywords = nil)
	    if keywords and current_page?(root_path)
	      	content_for?(:meta_keywords) ? content_for(:meta_keywords) : t('meta.default.keywords') # or default meta keyword
	    else
	      	content_for(:meta_keywords) { keywords }
	    end
	end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/index.html.slim
.body-head
	.container
		.row
			.jumbotron
			  h1.display-4 Hello, world!
			  p.lead This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
			  hr.my-4/
			  p It uses utility classes for typography and spacing to space content out within the larger container.
			  a.btn.btn-primary.btn-lg href="#" role="button"  Learn more
.body-filter
	.container
		.row
			.row.u-mt--30.u-mb--30
	          .col-sm-12
	            
.body-body
	.container
		.row
			.card-deck
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.
			    .card-footer
			      small.text-muted Last updated 3 mins ago
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This card has supporting text below as a natural lead-in to additional content.
			    .card-footer
			      small.text-muted Last updated 3 mins ago
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.
			    .card-footer
			      small.text-muted Last updated 3 mins ago

app/views/course/index.html.slim
.body-head
	.container
		.row
			.jumbotron
			  h1.display-4 Hello, world!
			  p.lead This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
			  hr.my-4/
			  p It uses utility classes for typography and spacing to space content out within the larger container.
			  a.btn.btn-primary.btn-lg href="#" role="button"  Learn more

.body-filter
	.container
		.row
			.row.u-mt--30.u-mb--30
	          .col-sm-12
	            
.body-body
	.container
		.row
			.card-deck
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.
			    .card-footer
			      small.text-muted Last updated 3 mins ago
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This card has supporting text below as a natural lead-in to additional content.
			    .card-footer
			      small.text-muted Last updated 3 mins ago
			  .card
			    img.card-img-top alt=("Card image cap") src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22239%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20239%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_164a6f1baa6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_164a6f1baa6%22%3E%3Crect%20width%3D%22239%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2288.7578125%22%20y%3D%2295.1%22%3E239x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" /
			    .card-body
			      h5.card-title Card title
			      p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.
			    .card-footer
			      small.text-muted Last updated 3 mins ago

app/views/home/index.html.slim
.body-head
	.container
		.row

.body-body
	.container
		.row

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = render "layouts/partials/hreflang"
    title = page_title
    meta name="description" content="#{yield :meta_description}"
    meta name="keywords" content="#{yield :meta_keywords}"
    = favicon_link_tag '/favicons/favicon.ico', rel: 'icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="author" content="Yusnardo Tendio"
    = yield :head
  
  body class="has-fc-offcanvas" data-controller="#{controller_path}" data-action="#{action_name}" data-locale="#{locale}"
    = render "layouts/modals/modal_login"
    header
        = render 'layouts/hellobar/info'
        = render "layouts/navbar/navbar"
        - if signed_in?
            | Signed in as: #{current_user.email}
            | \#{button_to 'Sign out', sign_out_path, method: :delete}
        - else
            = link_to 'Sign in', sign_in_path

        
        /= render "layouts/footer/footer"
    section
        #flash
            - flash.each do |key, value|
                div class=("flash #{key}") = value
        = yield

    

app/views/layouts/footer/_footer.html.slim
.fc-copyright
  .container
    .row
      .col-sm-6.fc-copyright__text
        p = t("footer.copyright.pm")
        ul.list-inline
          - (1..6).each do |i|
            li = image_tag "payment-method/pm-#{i}.png", class: "img-responsive", size: "60"
      
      .col-sm-6.fc-copyright__text
        p = t("footer.copyright.ss")
        ul.list-inline
          - (1..4).each do |i|
            li = image_tag "footer/ss-#{i}.png", class: "img-responsive", size: "60"
    
    .row
      .col-sm-6
        ul.list-inline.u-mt--10
          li
            span = t("footer.copyright.about")
    
    .row
      .col-sm-12
        ul.list-inline.u-mt--10
          li
            span = t("footer.copyright.text", :year => DateTime.now.year)
          li.text-danger = fa_icon 'heart'
          li
            span = t("footer.copyright.created")

app/views/layouts/hellobar/_info.html.slim
.fl-hellobar-info.visible-lg
  .container
    .row.fl-hellobar-info__content
      .col-sm-8
        ul.list-inline.u-mb--no
          li
            span.u-mr--10 = t("general.info.consult")
          li
            = fa_icon 'phone lg', class: "u-mr--5"
            span +62 82393073148
          li
            = fa_icon 'envelope-o lg', class: "u-mr--5"
            = mail_to t("general.info.mail")

      .col-sm-4.text-right
        ul.list-inline.u-mb--no
          li.dropdown.u-pr--no
            a.dropdown-toggle data-toggle="dropdown" href="#"
              - if I18n.locale.to_s == "id"
                = image_tag('flag/flag_of_id.png', size: '30x20', alt:'Indonesian')
              - else
                = image_tag('flag/flag_of_en.png', size: '30x20', alt:'English')
            ul.dropdown-menu.fl-hellobar-info__dropdown
              li.space 
                / = link_to params["locale"]="en", :"data-no-turbolink" => true do
                
                = link_to params.to_unsafe_h.merge(locale: "en"), :"data-no-turbolink" => true do
                  = image_tag('flag/flag_of_en.png', size: '30x20', alt:'Flag of English')
                  span.u-ml--5 = "English"
              li.space 
                / = link_to params["locale"]="id", :"data-no-turbolink" => true do
                = link_to params.to_unsafe_h.merge(locale: "id"), :"data-no-turbolink" => true do
                  = image_tag('flag/flag_of_id.png', size: '30x20', alt:'Flag of Indonesia')
                  span.u-ml--5 = "Indonesia"

app/views/layouts/modals/_modal_login.html.slim
.modal.fade.fc-modal-fs id="modal_login" tabindex="-1" role="dialog" aria-labelledby="modal_login_label"
  .modal-dialog.fc-modal-fs__dialog role="document"
    .modal-content.fc-modal-fs__content
      .modal-body
        .container
          .row
            .col-sm-6.col-center.u-mt-20   
              button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: 15px;"
                span aria-hidden="true" &times;       
              form#form_login_only action="#{session_path}"
                h1.fc-heading__bright--md.u-mt--30 = t('login.title_big')
                p.fc-subheading.u-mb--30 == t('login.title', :home_link => link_to('Sribu', root_path))
                = hidden_field_tag :redirect_url, request.original_url
                / Field username
                .form-group.with-icon
                  = text_field_tag :username, "", required: true, class: "form-control input-lg", id: 'username', :placeholder => t('login.placeholder.username'), :data => {validation: "length", :"validation-length" => "2-50", :"validation-error-msg" => t('login.error.username')}
                  span
                    = fa_icon 'user'

                / Field password
                .form-group.with-icon
                  = password_field_tag :password, "", required: true, class: "form-control input-lg", id: 'passsword', :placeholder => t('login.placeholder.password'), :data => {validation: "length", :"validation-length" => "min6", :"validation-error-msg" => t('login.error.password')}
                  span
                    = fa_icon 'lock'

                .form-group
                  / Remember me
                  span
                    / label.checkbox-inline
                    /   input type="checkbox" value="" = t('login.remember')
                  / Forgot password
                  / span.pull-right.fl-login__forgot
                  /   = link_to t("login.forgot"), new_reset_password_path

                / Submit login
                .form-group
                  = submit_tag t("general.link.login"), class: "btn btn-lg btn-block btn-success"

                .form-group
                  p.fl-login__signup == t('login.register', :register_link => link_to(t('general.link.register').downcase, sign_in_path))

app/views/layouts/navbar/_navbar.html.slim
.navbar.navbar-expand-lg.navbar-expand-md.bg-red   	
	#navbarNav.collapse.navbar-collapse
		.container.visible-lg
	    	.row
				ul.nav.navbar-nav.navbar-left
		    		li.nav-item.active
		    			a.navbar-brand.logo href="/" title="MafiaTech" MafiaTech
		      		li.nav-item
		        		span.nav-link = link_to t('general.link.course'), course_path
		      		li.nav-item
		        		span.nav-link = link_to t('general.link.blog'), blog_path
	        	ul.nav.navbar-nav.ml-auto.push-left
		        	li.nav-item
		        		span.nav-link
			        		= link_to "#", :'data-toggle' => 'modal', :'data-target' => '#modal_login' do 
			        			= t('general.link.login')
		      		li.nav-item
		        		span.nav-link = link_to t('general.link.register'), sign_up_path

app/views/layouts/partials/_hreflang.html.slim
- %w(en id).each do |lang|
  - query_params = request.query_parameters
  - query_params.merge!(locale: lang, only_path: false)
  link rel="alternate" hreflang="#{lang}" href="#{url_for(query_params)}"